Models/Reservas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace SCMotors.Models
{
        public class Reservas
        {
            [BsonId]
            [BsonRepresentation(BsonType.ObjectId)]
            public string Id { get; set; }

            [BsonElement("cliente_id")]
            [BsonRepresentation(BsonType.ObjectId)] 
            public string Cliente_id { get; set; }

            [BsonElement("modelo_auto")]
            public string Modelo_auto { get; set; }

            [Required]
            [BsonElement("detalles_reserva")]
            public string Detalles_reserva { get; set; }

            [BsonElement("estado")]
            public string Estado { get; set; }

    }
 }

Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using SCMotors.Models;

namespace SCMotors.Controllers
{
    public class ReservasController : Controller
    {
        private readonly Conexion _conexion;

        public ReservasController()
        {
            _conexion = new Conexion();
        }

        // GET: Reservas
        public ActionResult Index()
        {
            return View();
        }

        // GET: Reservas/List
        public ActionResult List()
        {
            var reservas = _conexion.ReservasCollection.Find(_ => true).ToList();
            return View(reservas);
        }

        // GET: Reservas/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "ID inválido.");
            }

            try
            {
                var reservas = _conexion.ReservasCollection.Find(r => r.Id == id).FirstOrDefault(); 

                if (reservas == null)
                {
                    return HttpNotFound("Cliente no encontrado.");
                }

                return View(reservas);
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"Error al obtener detalles del cliente (ID: {id}): {ex.Message}";
                return View("Error");
            }
        }


        // GET: Reservas/Create
        public ActionResult Create()
        {
            var clientes = _conexion.ClientesCollection
                            .Find(_ => true)
                            .Project(c => new SelectListItem
                            {
                                Value = c.Id,         
                                Text = c.Nombre       
                            })
                            .ToList();

            ViewBag.Clientes = clientes; 

            return View();
        }



        // POST: Reservas/Create
        [HttpPost]
        public ActionResult Create(Reservas reservas)
        {
            if (ModelState.IsValid)
            {
                reservas.Cliente_id = reservas.Cliente_id ?? ObjectId.Empty.ToString(); 
                _conexion.ReservasCollection.InsertOne(reservas);
                return RedirectToAction("Index");
            }

            var clientes = _conexion.ClientesCollection.Find(_ => true).ToList();
            ViewBag.Clientes = new SelectList(clientes, "_id", "Nombre"); 
            return View(reservas);
        }



        // GET: Reservas/Edit/5
        public ActionResult Edit(string id)
        {
            var reservas = _conexion.ReservasCollection
                .Find(r => r.Id == id)
                .FirstOrDefault();

            if (reservas == null)
            {
                return HttpNotFound();
            }

            // Obtener la lista de clientes
            var clientes = _conexion.ClientesCollection
                .Find(_ => true)
                .Project(c => new SelectListItem
                {
                    Value = c.Id,        
                    Text = c.Nombre      
                })
                .ToList();

            ViewBag.Clientes = clientes; 
            return View(reservas);
        }

        // POST: Reservas/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, Reservas reservas)
        {
            if (id != reservas.Id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                var filter = Builders<Reservas>.Filter.Eq(r => r.Id, id);
                _conexion.ReservasCollection.ReplaceOne(filter, reservas);

                return RedirectToAction("Index");
            }

            var clientes = _conexion.ClientesCollection
                .Find(_ => true)
                .Project(c => new SelectListItem
                {
                    Value = c.Id,
                    Text = c.Nombre
                })
                .ToList();

            ViewBag.Clientes = clientes;
            return View(reservas);
        }


        // GET: Reservas/Delete/5
        public ActionResult Delete(string id)
        {
            var reservas = _conexion.ReservasCollection
                .Find(r => r.Id == id)
                .FirstOrDefault();

            if (reservas == null)
            {
                return HttpNotFound();
            }

            return View(reservas);
        }

        // POST: Reservas/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, Reservas reservas)
        {
            try
            {
                var filter = Builders<Reservas>.Filter.Eq(r => r.Id, id);
                _conexion.ReservasCollection.DeleteOne(filter);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Reservas/Create.cshtml
@model SCMotors.Models.Reservas

@{
    ViewBag.Title = "Crear Reserva";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 class="text-center mb-4">Crear Nueva Reserva</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="card shadow-lg">
                    <div class="card-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Modelo_auto, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Modelo_auto, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Modelo_auto, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Cliente_id, "Cliente", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.DropDownList("Cliente_id", (IEnumerable<SelectListItem>)ViewBag.Clientes, "Seleccione un cliente", new { @class = "form-control form-control-lg" })
                                @Html.ValidationMessageFor(model => model.Cliente_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Detalles_reserva, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Detalles_reserva, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Detalles_reserva, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-9 offset-md-3">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Guardar Reserva</button>
                            </div>
                        </div>
                    </div>
                </div>
            }

            <div class="text-center mt-4">
                @Html.ActionLink("Regresar a la lista", "Index", new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
</div>

Views/Reservas/Delete.cshtml
@model SCMotors.Models.Reservas

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente_id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Modelo_auto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo_auto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detalles_reserva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detalles_reserva)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Reservas/Details.cshtml
@model SCMotors.Models.Reservas

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reservas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo_auto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo_auto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detalles_reserva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detalles_reserva)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Reservas/Edit.cshtml
@model SCMotors.Models.Reservas

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Reservas</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Cliente_id, "Cliente", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(
                model => model.Cliente_id,  
                (IEnumerable<SelectListItem>)ViewBag.Clientes,
                "Seleccione un cliente",
                new { @class = "form-control" }
            )
            @Html.ValidationMessageFor(model => model.Cliente_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Modelo_auto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Modelo_auto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Modelo_auto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Detalles_reserva, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Detalles_reserva, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Detalles_reserva, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Reservas/Index.cshtml
@{
    ViewBag.Title = "Gestión de Reservas";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        .navbar-dark {
            background-color: #2a3e53 !important;
        }

        .nav-link {
            color: white;
        }

        .navbar-toggler-icon {
            filter: invert(100%);
        }

        .header-options {
            background-color: #2a3e53;
            color: white;
            padding: 20px;
            border-radius: 5px;
        }

            .header-options a {
                color: white;
                margin-right: 15px;
            }

                .header-options a:hover {
                    text-decoration: none;
                    color: #f1f1f1;
                }

        .welcome-text {
            text-align: center;
            margin-bottom: 30px;
        }

            .welcome-text p {
                font-size: 1.2rem;
            }
    </style>
</head>
<body>
    <div class="welcome-text">
        <h1 class="mt-5">Bienvenido a la Gestión de Reservas</h1>
        <p>Utiliza las opciones del menú para gestionar los datos de las Reservas de manera eficiente.</p>
    </div>

    <div class="header-options text-center">
        <h2>Gestión de Reservas</h2>
        <a class="btn btn-outline-light" href="@Url.Action("Create", "Reservas")">Crear Reserva</a>
        <a class="btn btn-outline-light" href="@Url.Action("List", "Reservas")">Lista</a>
    </div>

    <div class="container mt-4">

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Reservas/List.cshtml
@model IEnumerable<SCMotors.Models.Reservas>

@{
    ViewBag.Title = "Lista de Reservas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Reservas</h2>

<p>
    @Html.ActionLink("Crear Nueva Reserva", "Create", new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Modelo de Auto</th>
            <th>Detalles de Reserva</th>
            <th>Estado</th>
            <th>Cliente ID</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Modelo_auto)</td>
                <td>@Html.DisplayFor(modelItem => item.Detalles_reserva)</td>
                <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                <td>@Html.DisplayFor(modelItem => item.Cliente_id)</td>
                <td>
                    <a href="@Url.Action("Edit", "Reservas", new { id = item.Id })" class="btn btn-warning btn-sm">Editar</a>
                    <a href="@Url.Action("Details", "Reservas", new { id = item.Id })" class="btn btn-info btn-sm">Detalles</a>
                    <a href="@Url.Action("Delete", "Reservas", new { id = item.Id })" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar esta reserva?')">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>