Models/Promociones.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace SCMotors.Models
{
    public class Promociones
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [Required]
        [BsonElement("nombre")]
        public string Nombre { get; set; }

        [Required]
        [BsonElement("descripción")]
        public string Descripción { get; set; }

        [Required]
        [BsonElement("tipo")]
        public string Tipo { get; set; }

        [Required]
        [BsonElement("porcentaje_descuento")]
        public int Porcentaje_descuento { get; set; }

        [Required]
        [BsonElement("estado")]
        public string Estado { get; set; }

    }
}

Controllers/PromocionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MongoDB.Driver;
using SCMotors.Models;

namespace SCMotors.Controllers
{
    public class PromocionesController : Controller
    {
        private readonly Conexion _conexion;

        public PromocionesController()
        {
            _conexion = new Conexion();
        }

        // GET: Promociones
        public ActionResult Index()
        {
            return View();
        }

        // GET: Promociones/List
        public ActionResult List()
        {
            var promociones = _conexion.PromocionesCollection.Find(_ => true).ToList();
            return View(promociones);
        }

        // GET: Promociones/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "ID inválido.");
            }

            try
            {
                var promociones = _conexion.PromocionesCollection.Find(p => p.Id == id).FirstOrDefault(); 

                if (promociones == null)
                {
                    return HttpNotFound("Cliente no encontrado.");
                }

                return View(promociones);
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"Error al obtener detalles del cliente (ID: {id}): {ex.Message}";
                return View("Error");
            }
        }


        // GET: Promociones/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Promociones/Create
        [HttpPost]
        public ActionResult Create(Promociones promociones)
        {
            if (ModelState.IsValid)
            {
                _conexion.PromocionesCollection.InsertOne(promociones);
                return RedirectToAction("Index");
            }

            return View(promociones);
        }

        // GET: Promociones/Edit/5
        public ActionResult Edit(string id)
        {
            var promociones = _conexion.PromocionesCollection
                .Find(p => p.Id == id)
                .FirstOrDefault();

            if (promociones == null)
            {
                return HttpNotFound();
            }

            return View(promociones);
        }

        // POST: Promociones/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, Promociones promociones)
        {
            if (id != promociones.Id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                var filter = Builders<Promociones>.Filter.Eq(p => p.Id, id);
                _conexion.PromocionesCollection.ReplaceOne(filter, promociones); 

                return RedirectToAction("Index");
            }

            return View(promociones);
        }


        // GET: Promociones/Delete/5
        public ActionResult Delete(string id)
        {
            var promociones = _conexion.PromocionesCollection
                .Find(p => p.Id == id)
                .FirstOrDefault();

            if (promociones == null)
            {
                return HttpNotFound();
            }

            return View(promociones);
        }

        // POST: Promociones/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, Promociones promociones)
        {
            try
            {
                var filter = Builders<Promociones>.Filter.Eq(p => p.Id, id);
                _conexion.PromocionesCollection.DeleteOne(filter);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Promociones/Create.cshtml
@model SCMotors.Models.Promociones

@{
    ViewBag.Title = "Crear Promoción";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 class="text-center mb-4">Crear Nueva Promoción</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="card shadow-lg">
                    <div class="card-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Descripción, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Descripción, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Descripción, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Porcentaje_descuento, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Porcentaje_descuento, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Porcentaje_descuento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-9 offset-md-3">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Guardar Promoción</button>
                            </div>
                        </div>
                    </div>
                </div>
            }

            <div class="text-center mt-4">
                @Html.ActionLink("Regresar a la lista", "Index", new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
</div>

Views/Promociones/Delete.cshtml
@model SCMotors.Models.Promociones

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Promociones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripción)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripción)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Porcentaje_descuento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Porcentaje_descuento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Promociones/Details.cshtml
@model SCMotors.Models.Promociones

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Promociones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripción)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripción)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Porcentaje_descuento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Porcentaje_descuento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Promociones/Edit.cshtml
@model SCMotors.Models.Promociones

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Promociones</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripción, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripción, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripción, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Porcentaje_descuento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Porcentaje_descuento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Porcentaje_descuento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Promociones/Index.cshtml
@{
    ViewBag.Title = "Gestión de Reservas";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        .navbar-dark {
            background-color: #2a3e53 !important;
        }

        .nav-link {
            color: white;
        }

        .navbar-toggler-icon {
            filter: invert(100%);
        }

        .header-options {
            background-color: #2a3e53;
            color: white;
            padding: 20px;
            border-radius: 5px;
        }

            .header-options a {
                color: white;
                margin-right: 15px;
            }

                .header-options a:hover {
                    text-decoration: none;
                    color: #f1f1f1;
                }

        .welcome-text {
            text-align: center;
            margin-bottom: 30px;
        }

            .welcome-text p {
                font-size: 1.2rem;
            }
    </style>
</head>
<body>
    <div class="welcome-text">
        <h1 class="mt-5">Bienvenido a la Gestión de Promociones</h1>
        <p>Utiliza las opciones del menú para gestionar los datos de las Promociones de manera eficiente.</p>
    </div>

    <div class="header-options text-center">
        <h2>Gestión de Promociones</h2>
        <a class="btn btn-outline-light" href="@Url.Action("Create", "Promociones")">Crear Promocion</a>
        <a class="btn btn-outline-light" href="@Url.Action("List", "Promociones")">Lista</a>
    </div>

    <div class="container mt-4">

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Promociones/List.cshtml
@model IEnumerable<SCMotors.Models.Promociones>

@{
    ViewBag.Title = "Lista de Promociones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Promociones</h2>

<p>
    @Html.ActionLink("Crear Nueva Promoción", "Create", new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Tipo</th>
            <th>% Descuento</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                <td>@Html.DisplayFor(modelItem => item.Descripción)</td>
                <td>@Html.DisplayFor(modelItem => item.Tipo)</td>
                <td>@Html.DisplayFor(modelItem => item.Porcentaje_descuento)</td>
                <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                <td>
                    <a href="@Url.Action("Edit", "Promociones", new { id = item.Id })" class="btn btn-warning btn-sm">Editar</a>
                    <a href="@Url.Action("Details", "Promociones", new { id = item.Id })" class="btn btn-info btn-sm">Detalles</a>
                    <a href="@Url.Action("Delete", "Promociones", new { id = item.Id })" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar esta promoción?')">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>