Models/Ventas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace SCMotors.Models
{
    public class Ventas
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [Required]
        [BsonElement("empleado")]
        public string Empleado { get; set; }

        [BsonElement("cliente")]
        public string Cliente { get; set; }

        [BsonElement("vehiculo_id")]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Vehiculo_id { get; set; }

        [Required]
        [BsonElement("total")]
        public int Total { get; set; }

    }
}

Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using SCMotors.Models;

namespace SCMotors.Controllers
{
    public class VentasController : Controller
    {
        private readonly Conexion _conexion;

        public VentasController()
        {
            _conexion = new Conexion();
        }

        // GET: Ventas
        public ActionResult Index()
        {
            return View();
        }

        // GET: Ventas/List
        public ActionResult List()
        {
            var ventas = _conexion.VentasCollection.Find(_ => true).ToList();
            return View(ventas);
        }

        // GET: Ventas/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "ID inválido.");
            }

            try
            {
                var ventas = _conexion.VentasCollection.Find(v => v.Id == id).FirstOrDefault();

                if (ventas == null)
                {
                    return HttpNotFound("Auto no encontrado.");
                }

                return View(ventas);
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"Error al obtener detalles del cliente (ID: {id}): {ex.Message}";
                return View("Error");
            }
        }


        // GET: Ventas/Create
        public ActionResult Create()
        {
            var autos = _conexion.AutosCollection
                            .Find(_ => true)
                            .Project(c => new SelectListItem
                            {
                                Value = c.Id,
                                Text = c.Modelo
                            })
                            .ToList();

            ViewBag.Autos = autos;

            return View();
        }



        // POST: Ventas/Create
        [HttpPost]
        public ActionResult Create(Ventas ventas)
        {
            if (ModelState.IsValid)
            {
                ventas.Vehiculo_id = ventas.Vehiculo_id ?? ObjectId.Empty.ToString();
                _conexion.VentasCollection.InsertOne(ventas);
                return RedirectToAction("Index");
            }

            var autos = _conexion.AutosCollection.Find(_ => true).ToList();
            ViewBag.Autos = new SelectList(autos, "_id", "Modelo");
            return View(ventas);
        }



        // GET: Ventas/Edit/5
        public ActionResult Edit(string id)
        {
            var Ventas = _conexion.VentasCollection
                .Find(v => v.Id == id)
                .FirstOrDefault();

            if (Ventas == null)
            {
                return HttpNotFound();
            }

            var autos = _conexion.AutosCollection
                .Find(_ => true)
                .Project(c => new SelectListItem
                {
                    Value = c.Id,
                    Text = c.Modelo
                })
                .ToList();

            ViewBag.Autos = autos;
            return View(Ventas);
        }

        // POST: Ventas/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, Ventas ventas)
        {
            if (id != ventas.Id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                var filter = Builders<Ventas>.Filter.Eq(r => r.Id, id);
                _conexion.VentasCollection.ReplaceOne(filter, ventas);

                return RedirectToAction("Index");
            }

            var autos = _conexion.AutosCollection
                .Find(_ => true)
                .Project(c => new SelectListItem
                {
                    Value = c.Id,
                    Text = c.Modelo
                })
                .ToList();

            ViewBag.Autos = autos;
            return View(ventas);
        }


        // GET: Ventas/Delete/5
        public ActionResult Delete(string id)
        {
            var ventas = _conexion.VentasCollection
                .Find(v => v.Id == id)
                .FirstOrDefault();

            if (ventas == null)
            {
                return HttpNotFound();
            }

            return View(ventas);
        }

        // POST: Ventas/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, Ventas ventas)
        {
            try
            {
                var filter = Builders<Ventas>.Filter.Eq(v => v.Id, id);
                _conexion.VentasCollection.DeleteOne(filter);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Ventas/Create.cshtml
@model SCMotors.Models.Ventas

@{
    ViewBag.Title = "Crear Venta";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 class="text-center mb-4">Crear Nueva Venta</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="card shadow-lg">
                    <div class="card-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Empleado, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Empleado, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Empleado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Cliente, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Cliente, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Cliente, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Vehiculo_id, "Auto", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.DropDownList("Vehiculo_id", (IEnumerable<SelectListItem>)ViewBag.Autos, "Seleccione un Auto", new { @class = "form-control form-control-lg" })
                                @Html.ValidationMessageFor(model => model.Vehiculo_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-9 offset-md-3">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Guardar Venta</button>
                            </div>
                        </div>
                    </div>
                </div>
            }

            <div class="text-center mt-4">
                @Html.ActionLink("Regresar a la lista", "Index", new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
</div>

Views/Ventas/Delete.cshtml
@model SCMotors.Models.Ventas

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ventas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehiculo_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehiculo_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Ventas/Details.cshtml
@model SCMotors.Models.Ventas

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ventas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehiculo_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehiculo_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Ventas/Edit.cshtml
@model SCMotors.Models.Ventas

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ventas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Empleado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cliente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vehiculo_id, "Auto", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
                    model => model.Vehiculo_id,
                    (IEnumerable<SelectListItem>)ViewBag.Autos,
                    "Seleccione un Auto",
                    new { @class = "form-control" }
                )
                @Html.ValidationMessageFor(model => model.Vehiculo_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Ventas/Index.cshtml
@{
    ViewBag.Title = "Gestión de Ventas";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        .navbar-dark {
            background-color: #2a3e53 !important;
        }

        .nav-link {
            color: white;
        }

        .navbar-toggler-icon {
            filter: invert(100%);
        }

        .header-options {
            background-color: #2a3e53;
            color: white;
            padding: 20px;
            border-radius: 5px;
        }

            .header-options a {
                color: white;
                margin-right: 15px;
            }

                .header-options a:hover {
                    text-decoration: none;
                    color: #f1f1f1;
                }

        .welcome-text {
            text-align: center;
            margin-bottom: 30px;
        }

            .welcome-text p {
                font-size: 1.2rem;
            }
    </style>
</head>
<body>
    <div class="welcome-text">
        <h1 class="mt-5">Bienvenido a la Gestión de Autos</h1>
        <p>Utiliza las opciones del menú para gestionar los datos de las Autos de manera eficiente.</p>
    </div>

    <div class="header-options text-center">
        <h2>Gestión de Ventas</h2>
        <a class="btn btn-outline-light" href="@Url.Action("Create", "Ventas")">Agregar Venta</a>
        <a class="btn btn-outline-light" href="@Url.Action("List", "Ventas")">Lista</a>
    </div>

    <div class="container mt-4">

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Ventas/List.cshtml
@model IEnumerable<SCMotors.Models.Ventas>

@{
    ViewBag.Title = "Lista de Ventas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Ventas</h2>

<p>
    @Html.ActionLink("Crear Nueva Venta", "Create", new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Empleado</th>
            <th>Cliente</th>
            <th>Vehículo</th>
            <th>Total</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Empleado)</td>
                <td>@Html.DisplayFor(modelItem => item.Cliente)</td>
                <td>@Html.DisplayFor(modelItem => item.Vehiculo_id)</td>
                <td>@Html.DisplayFor(modelItem => item.Total)</td>
                <td>
                    <a href="@Url.Action("Edit", "Ventas", new { id = item.Id })" class="btn btn-warning btn-sm">Editar</a>
                    <a href="@Url.Action("Details", "Ventas", new { id = item.Id })" class="btn btn-info btn-sm">Detalles</a>
                    <a href="@Url.Action("Delete", "Ventas", new { id = item.Id })" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar esta venta?')">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>