Models/Reclamos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace SCMotors.Models
{
        public class Reclamos
        {
            [BsonId]
            [BsonRepresentation(BsonType.ObjectId)]
            public string Id { get; set; }

            [BsonElement("cliente_id")]
            [BsonRepresentation(BsonType.ObjectId)]
            public string Cliente_id { get; set; }

            [Required]
            [BsonElement("tipo_reclamo")]
            public string Tipo_reclamo { get; set; }

            [BsonElement("detalle")]
            public string Detalle { get; set; }

            [Required]
            [BsonElement("estado")]
            public string Estado { get; set; }

            [Required]
            [BsonElement("respuesta")]
            public string Respuesta { get; set; }

        }
    }

Controllers/ReclamosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using SCMotors.Models;

namespace SCMotors.Controllers
{
    public class ReclamosController : Controller
    {
        private readonly Conexion _conexion;

        public ReclamosController()
        {
            _conexion = new Conexion();
        }

        // GET: Reclamos
        public ActionResult Index()
        {
            return View();
        }

        // GET: Reclamos/List
        public ActionResult List()
        {
            var reclamos = _conexion.ReclamosCollection.Find(_ => true).ToList();
            return View(reclamos);
        }

        // GET: Reclamos/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "ID inválido.");
            }

            try
            {
                var reclamos = _conexion.ReclamosCollection.Find(r => r.Id == id).FirstOrDefault();

                if (reclamos == null)
                {
                    return HttpNotFound("Cliente no encontrado.");
                }

                return View(reclamos);
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"Error al obtener detalles del cliente (ID: {id}): {ex.Message}";
                return View("Error");
            }
        }


        // GET: Reclamos/Create
        public ActionResult Create()
        {
            var clientes = _conexion.ClientesCollection
                            .Find(_ => true)
                            .Project(c => new SelectListItem
                            {
                                Value = c.Id,
                                Text = c.Nombre
                            })
                            .ToList();

            ViewBag.Clientes = clientes;

            return View();
        }



        // POST: Reclamos/Create
        [HttpPost]
        public ActionResult Create(Reclamos reclamos)
        {
            if (ModelState.IsValid)
            {
                reclamos.Cliente_id = reclamos.Cliente_id ?? ObjectId.Empty.ToString();
                _conexion.ReclamosCollection.InsertOne(reclamos);
                return RedirectToAction("Index");
            }

            var clientes = _conexion.ClientesCollection.Find(_ => true).ToList();
            ViewBag.Clientes = new SelectList(clientes, "_id", "Nombre");
            return View(reclamos);
        }



        // GET: Reclamos/Edit/5
        public ActionResult Edit(string id)
        {
            var reclamos = _conexion.ReclamosCollection
                .Find(r => r.Id == id)
                .FirstOrDefault();

            if (reclamos == null)
            {
                return HttpNotFound();
            }

            // Obtener la lista de clientes
            var clientes = _conexion.ClientesCollection
                .Find(_ => true)
                .Project(c => new SelectListItem
                {
                    Value = c.Id,
                    Text = c.Nombre
                })
                .ToList();

            ViewBag.Clientes = clientes;
            return View(reclamos);
        }

        // POST: Reclamos/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, Reclamos reclamos)
        {
            if (id != reclamos.Id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                var filter = Builders<Reclamos>.Filter.Eq(r => r.Id, id);
                _conexion.ReclamosCollection.ReplaceOne(filter, reclamos);

                return RedirectToAction("Index");
            }

            var clientes = _conexion.ClientesCollection
                .Find(_ => true)
                .Project(c => new SelectListItem
                {
                    Value = c.Id,
                    Text = c.Nombre
                })
                .ToList();

            ViewBag.Clientes = clientes;
            return View(reclamos);
        }


        // GET: Reclamos/Delete/5
        public ActionResult Delete(string id)
        {
            var reclamos = _conexion.ReclamosCollection
                .Find(r => r.Id == id)
                .FirstOrDefault();

            if (reclamos == null)
            {
                return HttpNotFound();
            }

            return View(reclamos);
        }

        // POST: Reclamos/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, Reclamos reclamos)
        {
            try
            {
                var filter = Builders<Reclamos>.Filter.Eq(r => r.Id, id);
                _conexion.ReclamosCollection.DeleteOne(filter);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Reclamos/Create.cshtml
@model SCMotors.Models.Reclamos

@{
    ViewBag.Title = "Crear Reclamo";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 class="text-center mb-4">Crear Nuevo Reclamo</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="card shadow-lg">
                    <div class="card-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Cliente_id, "Cliente", htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.DropDownList("Cliente_id", (IEnumerable<SelectListItem>)ViewBag.Clientes, "Seleccione un cliente", new { @class = "form-control form-control-lg" })
                                @Html.ValidationMessageFor(model => model.Cliente_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Tipo_reclamo, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Tipo_reclamo, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Tipo_reclamo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            @Html.LabelFor(model => model.Respuesta, htmlAttributes: new { @class = "col-md-3 col-form-label text-md-right" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Respuesta, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                @Html.ValidationMessageFor(model => model.Respuesta, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-9 offset-md-3">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Guardar Reclamo</button>
                            </div>
                        </div>
                    </div>
                </div>
            }

            <div class="text-center mt-4">
                @Html.ActionLink("Regresar a la lista", "Index", new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
</div>

Views/Reclamos/Delete.cshtml
@model SCMotors.Models.Reclamos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reclamos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_reclamo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_reclamo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detalle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detalle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Respuesta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Respuesta)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Reclamos/Details.cshtml
@model SCMotors.Models.Reclamos

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reclamos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_reclamo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_reclamo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detalle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detalle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Respuesta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Respuesta)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Reclamos/Edit.cshtml
@model SCMotors.Models.Reclamos

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reclamos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
        @Html.LabelFor(model => model.Cliente_id, "Cliente", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            @Html.DropDownList("Cliente_id", (IEnumerable<SelectListItem>)ViewBag.Clientes, "Seleccione un cliente", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Cliente_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo_reclamo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo_reclamo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo_reclamo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Respuesta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Respuesta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Respuesta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Reclamos/Index.cshtml
@{
    ViewBag.Title = "Gestión de Reclamos";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        .navbar-dark {
            background-color: #2a3e53 !important;
        }

        .nav-link {
            color: white;
        }

        .navbar-toggler-icon {
            filter: invert(100%);
        }

        .header-options {
            background-color: #2a3e53;
            color: white;
            padding: 20px;
            border-radius: 5px;
        }

            .header-options a {
                color: white;
                margin-right: 15px;
            }

                .header-options a:hover {
                    text-decoration: none;
                    color: #f1f1f1;
                }

        .welcome-text {
            text-align: center;
            margin-bottom: 30px;
        }

            .welcome-text p {
                font-size: 1.2rem;
            }
    </style>
</head>
<body>
    <div class="welcome-text">
        <h1 class="mt-5">Bienvenido a la Gestión de Reclamos</h1>
        <p>Utiliza las opciones del menú para gestionar los datos de las Reclamos de manera eficiente.</p>
    </div>

    <div class="header-options text-center">
        <h2>Gestión de Reclamos</h2>
        <a class="btn btn-outline-light" href="@Url.Action("Create", "Reclamos")">Crear Reclamo</a>
        <a class="btn btn-outline-light" href="@Url.Action("List", "Reclamos")">Lista</a>
    </div>

    <div class="container mt-4">

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Reclamos/List.cshtml
@model IEnumerable<SCMotors.Models.Reclamos>

@{
    ViewBag.Title = "Lista de Reclamos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Reclamos</h2>

<p>
    @Html.ActionLink("Crear Nuevo Reclamo", "Create", new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Cliente ID</th>
            <th>Tipo de Reclamo</th>
            <th>Detalle</th>
            <th>Estado</th>
            <th>Respuesta</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Cliente_id)</td>
                <td>@Html.DisplayFor(modelItem => item.Tipo_reclamo)</td>
                <td>@Html.DisplayFor(modelItem => item.Detalle)</td>
                <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                <td>@Html.DisplayFor(modelItem => item.Respuesta)</td>
                <td>
                    <a href="@Url.Action("Edit", "Reclamos", new { id = item.Id })" class="btn btn-warning btn-sm">Editar</a>
                    <a href="@Url.Action("Details", "Reclamos", new { id = item.Id })" class="btn btn-info btn-sm">Detalles</a>
                    <a href="@Url.Action("Delete", "Reclamos", new { id = item.Id })" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar este reclamo?')">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>